spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ''
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

server:
  port: 8080